### ISSUE TITLE
Obsolete .po and .mo files need to be removed from plugin installer.

### ISSUE THREAD

**Issue by freemp** [pippinsplugins/Transients-Manager#20]
The installer used by Wordpress for installing and updating the plugin still contains the obsolete pw-transients-manager-en.po and pw-transients-manager-en.mo files.

**Comment by pippinsplugins** [comment]
Fixed!

**Comment by freemp** [comment]
Not fixed! Check your zip download file.

**Comment by pippinsplugins** [comment]
Ah, they were left in the SVN. I'm not concerned about those.

**Comment by freemp** [comment]
Well, you should be. It is what's being delivered.

**Comment by pippinsplugins** [comment]
Having `en` mo files causes zero issues. What's the problem with them?

**Comment by freemp** [comment]
You're sending useless junk to everybody who's installing your plugin.

**Comment by pippinsplugins** [comment]
No I'm not, I'm sending the language files for the plugin.

Tackle bigger problems in the world.
