### ISSUE TITLE
Possible to delete transients outside of the plugin by calling the PW_Transients_Manager class?

### ISSUE THREAD

**Issue by chrisblakley** [pippinsplugins/Transients-Manager#36]
I'm trying to come up with an easy way to delete transients with an expiration on the `save_post` hook. I'd love to be able to just call up one of your private functions (if the plugin is activated).

Looks like the method/function I'd want is `delete_transients_with_expirations()`, but since it's private I'm not able to call it directly. I could call `process_actions()` but I can't pass any parameters to it since it's only looking for the `$_REQUEST['action']`.

Any chance we could enhance the `process_actions()` function to accept a parameter, and have it check for that parameter or `$_REQUEST['action']`?

I could probably put a pull request together if it would make things easier. That is, if this functionality doesn't already exist somehow that I'm overlooking...

It was easy enough to modify a few lines, so I made an example in this pull request: https://github.com/pippinsplugins/Transients-Manager/pull/37

**Comment by pippinsplugins** [comment]
I like that idea.

How about instead of making `process_actions` accept a parameter, I just make those methods public. That seems a bit cleaner.

Would that work for you?

**Comment by chrisblakley** [comment]
Yeah that works for me- didn't want to suggest a change like that without knowing more background about the plugin.
