### ISSUE TITLE
set_site_transient() transients don't get deleted on WP Multisite

### ISSUE THREAD

**Issue by peter-2015** [pippinsplugins/Transients-Manager#39]
Transients for network wide when using WP Multisite don't get deleted. 

The site transients are stored in the db_prefix_sitemeta table in WordPress database.

I can delete using the other plugins but prefer your plugin because its much more user friendly. 

Please consider adding this the capability to delete site network wide transients. 

Many thanks for the great plugin.

**Comment by pippinsplugins** [comment]
@peter-2015 I have not seen this happen. Are you referring to `set_site_transient()`?

**Comment by peter-2015** [comment]
Yes, its the `set_site_transient()`

**Comment by pippinsplugins** [comment]
This should be fixed now https://github.com/pippinsplugins/Transients-Manager/commit/e5bf93c8424e76b32d433c3a750c74a9e3a05d6c
