### ISSUE TITLE
Update to support w.org translations

### ISSUE THREAD

**Issue by brashrebel** [pippinsplugins/Transients-Manager#40]
See details [here](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/). If we ditch `load_plugin_textdomain()`, add the domain and path to the header, change the domain to match the slug and require WP 4.6 or higher we can let community translations on w.org work instead of shipping them ourselves.

**Comment by cfoellmann** [comment]
ME again. Sorry for screwing this up.
The wp.org glotpress import failed because the used text-domain `pw-transients-manager` is not the same as the plugin-slug on wp.org 👿 

A complete change of all text-domain references need to be done

**Comment by pippinsplugins** [comment]
Thanks @cfoellmann! I've finally merged and deployed this.
