### ISSUE TITLE
WP.org is Out of sync

### ISSUE THREAD

**Issue by szepeviktor** [pippinsplugins/Transients-Manager#47]
Hello @pippinsplugins !

WP.org contains an old translation already removed here
https://plugins.trac.wordpress.org/browser/transients-manager/trunk/languages/pw-transients-manager-en.po

v1.7.5 is not tagged
https://plugins.trac.wordpress.org/browser/transients-manager/tags

Could you fix these?

**Comment by pippinsplugins** [comment]
Fixed!

**Comment by szepeviktor** [comment]
Thanks.
